### ISSUE TITLE
It just stops, and i thought I could make queues

### ISSUE THREAD

**Issue by polyinnovator** [koljapluemer/obsidian-the-queue#2]
![image](https://github.com/koljapluemer/obsidian-the-queue/assets/40401528/140051cd-46c6-4ab6-9d91-131a04a8117f)

After I do one item on the queue it just stops, even when I click out and go back in.

I wanted to make a queue for my habits, and a queue for my content production.

**Comment by koljapluemer** [comment]
Hi, thank your for testing and for your bug report!

Could you elaborate what exactly happens and maybe provide more screenshots? The output from the developer console (accessible with `Cmd+Option+J` or `Ctrl+Shift+I`) would also be very helpful.

I'd love to work on this problem, but it is very hard to pinpoint the problem from my side...

**Comment by polyinnovator** [comment]
Unfortunately I uninstalled so the logs are probably gone. I might be able to reproduce but Idk. It just simply doesn't continue. And sometimes it would just freeze on a blank box. I also sorta thought I could make my own queues, which was why I downloaded.  I wanted to make a queue to plan out my content, basically a prioritization list.
    On Tuesday, June 18, 2024 at 12:50:11 PM CDT, Kolja Sam ***@***.***> wrote:  
 
 


Hi, thank your for testing and for your bug report!

Could you elaborate what exactly happens and maybe provide more screenshots? The output from the developer console (accessible with Cmd+Option+J or Ctrl+Shift+I) would also be very helpful.

I'd love to work on this problem, but it is very hard to pinpoint the problem from my side...

**Comment by koljapluemer** [comment]
I see, thank you.

I will close this issue for now, but I recorded the problem in my bug tracker and if I manage to pinpoint it, I will fix it in a future version :)
